services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - '5050:80'
    restart: always
